version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8082}:8000"
    environment:
      # Django Core
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      
      # External Database Configuration
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      
      # AWS Configuration
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REKOGNITION_ACCESS_KEY_ID=${AWS_REKOGNITION_ACCESS_KEY_ID}
      - AWS_REKOGNITION_SECRET_ACCESS_KEY=${AWS_REKOGNITION_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_FACE_BUCKET=${AWS_S3_FACE_BUCKET}
      - AWS_S3_IMAGE_BUCKET=${AWS_S3_IMAGE_BUCKET}
      
      # OCR Configuration
      - OCR_MIN_CONFIDENCE=${OCR_MIN_CONFIDENCE:-80}
      - FACE_MIN_CONFIDENCE=${FACE_MIN_CONFIDENCE:-95}
      
      # Security & Access
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME:-iallamadas@universidadisep.com}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-iallamadas@universidadisep.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-Veronica023_}
      
      # Coolify Specific
      - COOLIFY_URL=${COOLIFY_URL:-http://localhost:8000}
      - COOLIFY_BRANCH=${COOLIFY_BRANCH:-main}
    
    volumes:
      - static_volume:/app/static
      - ./logs:/app/logs
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "python", "manage.py", "check", "--database", "default"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Coolify labels for better management
    labels:
      - "coolify.managed=true"
      - "coolify.version=1.0"
      - "coolify.service=onboarding-api"
      - "coolify.database=external"

volumes:
  static_volume:

# Network configuration for Coolify
networks:
  default:
    name: coolify
