# Generated by Django 4.2.16 on 2025-08-12 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Lista_name", models.CharField(max_length=10)),
                ("author_name", models.CharField(max_length=10)),
                ("Lista_price", models.IntegerField()),
                ("Lista_quantity", models.IntegerField()),
            ],
            options={
                "db_table": "apirest_lista",
            },
        ),
        migrations.CreateModel(
            name="llegadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("String", models.CharField(max_length=255)),
                ("check_status", models.IntegerField()),
            ],
            options={
                "db_table": "apirest_llegadas",
            },
        ),
        migrations.CreateModel(
            name="llegadas2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "string_income",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(7)],
                    ),
                ),
            ],
            options={
                "db_table": "apirest_llegadas2",
            },
        ),
        migrations.CreateModel(
            name="llegaface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faceselfie", models.CharField(max_length=255)),
                ("ocrident", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "apirest_llegaface",
            },
        ),
        migrations.CreateModel(
            name="puntaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje_Max", models.IntegerField()),
            ],
            options={
                "db_table": "apirest_puntaje",
            },
        ),
        migrations.CreateModel(
            name="puntaje_face",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje_Max", models.IntegerField()),
            ],
            options={
                "db_table": "apirest_puntaje_face",
            },
        ),
        migrations.CreateModel(
            name="puntaje_ocr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje_Max", models.IntegerField()),
            ],
            options={
                "db_table": "apirest_puntaje_ocr",
            },
        ),
        migrations.CreateModel(
            name="restrictiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "also_known_as",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("program", models.CharField(blank=True, max_length=255, null=True)),
                ("list", models.CharField(blank=True, max_length=255, null=True)),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("edad", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "citizenship",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("addresses", models.CharField(blank=True, max_length=255, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "state_province",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sanction_list",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hiperlik", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "apirest_restrictiva",
            },
        ),
        migrations.CreateModel(
            name="resultados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("nombres", models.CharField(max_length=255)),
                ("Puntos", models.IntegerField()),
                ("Lista_Sanciones", models.CharField(max_length=255)),
                ("Prospecto", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "apirest_resultados",
            },
        ),
    ]
